name: Health
on:
  pull_request:

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prettier check
        run: npx prettier --check .
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Get dependencies
        run: dart pub get
      - name: Verify generated code is up-to-date
        run: |
          dart run build_runner build --delete-conflicting-outputs
          git diff --exit-code
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze code
        run: dart analyze --fatal-infos --fatal-warnings

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: git submodule update --init
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Test dartdoc_builder
        run: dart test
        working-directory: dartdoc_builder
      - name: Test pubdoc
        run: dart test
        working-directory: pubdoc
